// V3 AWS IoT Secure Tunneling wire schema. Vendored from the V3
// WebSocket Protocol Guide so the source proxy can decode/encode frames
// independently of any third-party reference implementation.
//
// One Message type carries every wire frame; the discriminated Type
// enum identifies which fields are meaningful per frame kind. Field
// numbers are AWS-defined and must not change.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v3.proto

package securetunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type discriminates the frame kind. Values are AWS-defined; do not
// reorder.
type Type int32

const (
	Type_UNKNOWN          Type = 0
	Type_DATA             Type = 1
	Type_STREAM_START     Type = 2
	Type_STREAM_RESET     Type = 3
	Type_SESSION_RESET    Type = 4
	Type_SERVICE_IDS      Type = 5
	Type_CONNECTION_START Type = 6
	Type_CONNECTION_RESET Type = 7
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "DATA",
		2: "STREAM_START",
		3: "STREAM_RESET",
		4: "SESSION_RESET",
		5: "SERVICE_IDS",
		6: "CONNECTION_START",
		7: "CONNECTION_RESET",
	}
	Type_value = map[string]int32{
		"UNKNOWN":          0,
		"DATA":             1,
		"STREAM_START":     2,
		"STREAM_RESET":     3,
		"SESSION_RESET":    4,
		"SERVICE_IDS":      5,
		"CONNECTION_START": 6,
		"CONNECTION_RESET": 7,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_v3_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_v3_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_v3_proto_rawDescGZIP(), []int{0}
}

// Message is the single envelope the V3 subprotocol carries. It is
// length-prefixed (2-byte big-endian) on the wire ahead of the encoded
// protobuf bytes; the WebSocket binary-frame boundary is independent of
// the length-prefixed envelope (one WebSocket frame can carry zero, one,
// or several envelopes; an envelope can span WebSocket frames).
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type is the frame kind. See the Type enum for valid values.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=securetunnel.v3.Type" json:"type,omitempty"`
	// StreamId disambiguates concurrent streams within a service. Source
	// assigns a fresh non-zero value when initiating a stream via
	// STREAM_START; subsequent DATA / STREAM_RESET frames carry the same
	// value.
	StreamId int32 `protobuf:"varint,2,opt,name=streamId,proto3" json:"streamId,omitempty"`
	// Ignorable lets a peer mark a frame as discardable if the receiver
	// does not understand it. The source proxy in v1 ignores this flag
	// when sending (sets false on outgoing frames) and respects it on
	// incoming frames (unknown frame kinds with ignorable=true are
	// dropped silently rather than terminating the session).
	Ignorable bool `protobuf:"varint,3,opt,name=ignorable,proto3" json:"ignorable,omitempty"`
	// Payload is the data byte slice for DATA frames. Empty for control
	// frames.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// ServiceId names the destination service this frame targets. v1
	// single-service tunnels populate this with "SSH" on outgoing frames
	// and validate the value on incoming frames.
	ServiceId string `protobuf:"bytes,5,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	// AvailableServiceIds is the destination's published list of
	// service-ids on the SERVICE_IDS frame emitted on connection. The
	// source validates this list contains the expected service-id.
	AvailableServiceIds []string `protobuf:"bytes,6,rep,name=availableServiceIds,proto3" json:"availableServiceIds,omitempty"`
	// ConnectionId disambiguates concurrent connections within a single
	// stream. v1 ships single-connection-per-stream so this is left at
	// its zero value (the protocol treats absent connectionId as
	// connectionId=1 per the V3 guide).
	ConnectionId  int32 `protobuf:"varint,7,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v3_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_UNKNOWN
}

func (x *Message) GetStreamId() int32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Message) GetIgnorable() bool {
	if x != nil {
		return x.Ignorable
	}
	return false
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Message) GetAvailableServiceIds() []string {
	if x != nil {
		return x.AvailableServiceIds
	}
	return nil
}

func (x *Message) GetConnectionId() int32 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

var File_v3_proto protoreflect.FileDescriptor

const file_v3_proto_rawDesc = "" +
	"\n" +
	"\bv3.proto\x12\x0fsecuretunnel.v3\"\xfc\x01\n" +
	"\aMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.securetunnel.v3.TypeR\x04type\x12\x1a\n" +
	"\bstreamId\x18\x02 \x01(\x05R\bstreamId\x12\x1c\n" +
	"\tignorable\x18\x03 \x01(\bR\tignorable\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\tserviceId\x18\x05 \x01(\tR\tserviceId\x120\n" +
	"\x13availableServiceIds\x18\x06 \x03(\tR\x13availableServiceIds\x12\"\n" +
	"\fconnectionId\x18\a \x01(\x05R\fconnectionId*\x91\x01\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\x10\n" +
	"\fSTREAM_START\x10\x02\x12\x10\n" +
	"\fSTREAM_RESET\x10\x03\x12\x11\n" +
	"\rSESSION_RESET\x10\x04\x12\x0f\n" +
	"\vSERVICE_IDS\x10\x05\x12\x14\n" +
	"\x10CONNECTION_START\x10\x06\x12\x14\n" +
	"\x10CONNECTION_RESET\x10\aBMZKgithub.com/atomicgravity/postern/internal/securetunnel/proto;securetunnelpbb\x06proto3"

var (
	file_v3_proto_rawDescOnce sync.Once
	file_v3_proto_rawDescData []byte
)

func file_v3_proto_rawDescGZIP() []byte {
	file_v3_proto_rawDescOnce.Do(func() {
		file_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v3_proto_rawDesc), len(file_v3_proto_rawDesc)))
	})
	return file_v3_proto_rawDescData
}

var file_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v3_proto_goTypes = []any{
	(Type)(0),       // 0: securetunnel.v3.Type
	(*Message)(nil), // 1: securetunnel.v3.Message
}
var file_v3_proto_depIdxs = []int32{
	0, // 0: securetunnel.v3.Message.type:type_name -> securetunnel.v3.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v3_proto_init() }
func file_v3_proto_init() {
	if File_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v3_proto_rawDesc), len(file_v3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v3_proto_goTypes,
		DependencyIndexes: file_v3_proto_depIdxs,
		EnumInfos:         file_v3_proto_enumTypes,
		MessageInfos:      file_v3_proto_msgTypes,
	}.Build()
	File_v3_proto = out.File
	file_v3_proto_goTypes = nil
	file_v3_proto_depIdxs = nil
}
